apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi
